apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceappwilliams-deployment-az
  labels:
    app: myinsuranceappwilliams
spec:
  replicas: 8
  selector:
    matchLabels:
      app: myinsuranceappwilliams
  template:
    metadata:
      labels:
        app: myinsuranceappwilliams
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: myinsuranceappwilliams-deployment-az
        image:  hackathonimages.azurecr.io/myinsuranceappwilliams:v8
        ports:
        - name: http
          containerPort: 5000