apiVersion: v1
kind: Service
metadata:
  name: myinsuranceappwilliams-service-az
  labels:
    app: myinsuranceappwilliams
spec:
  type: NodePort
  selector:
    app: myinsuranceappwilliams
  ports:
  - port: 50050
    targetPort: http
    nodePort: 32410
    protocol: TCP    
    name: http